import type { Metadata } from "next";
import "@/index.css"; // Assuming your global styles are here
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "Idea Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
