import type { Metadata } from "next";
import "@/index.css"; // Assuming your global styles are here

export const metadata: Metadata = {
  title: "Idea Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return <html lang="en"><body suppressHydrationWarning={true}>{children}</body></html>;
}
